app_name: payments.api.ch.gov.uk	
group: api	
# XXX Make sure all services with /payments/ based routes have a weight LOWER than 1000	
weight: 900	
routes:	
  1: ^/payments
  2: ^/payments/.*
  3: ^/private/payments/.*
