// Code generated by MockGen. DO NOT EDIT.
// Source: service/gov_pay.go

// Package service is a generated GoMock package.
package service

import (
	models "github.com/companieshouse/payments.api.ch.gov.uk/models"
	gomock "github.com/golang/mock/gomock"
	http "net/http"
	reflect "reflect"
)

// MockProviderService is a mock of ProviderService interface
type MockProviderService struct {
	ctrl     *gomock.Controller
	recorder *MockProviderServiceMockRecorder
}

// MockProviderServiceMockRecorder is the mock recorder for MockProviderService
type MockProviderServiceMockRecorder struct {
	mock *MockProviderService
}

// NewMockProviderService creates a new mock instance
func NewMockProviderService(ctrl *gomock.Controller) *MockProviderService {
	mock := &MockProviderService{ctrl: ctrl}
	mock.recorder = &MockProviderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockProviderService) EXPECT() *MockProviderServiceMockRecorder {
	return m.recorder
}

// CheckProvider mocks base method
func (m *MockProviderService) CheckProvider(paymentResource *models.PaymentResourceRest) (*models.StatusResponse, ResponseType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckProvider", paymentResource)
	ret0, _ := ret[0].(*models.StatusResponse)
	ret1, _ := ret[1].(ResponseType)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckProvider indicates an expected call of CheckProvider
func (mr *MockProviderServiceMockRecorder) CheckProvider(paymentResource interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckProvider", reflect.TypeOf((*MockProviderService)(nil).CheckProvider), paymentResource)
}

// GenerateNextURLGovPay mocks base method
func (m *MockProviderService) GenerateNextURLGovPay(req *http.Request, paymentResource *models.PaymentResourceRest) (string, ResponseType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateNextURLGovPay", req, paymentResource)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(ResponseType)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateNextURLGovPay indicates an expected call of GenerateNextURLGovPay
func (mr *MockProviderServiceMockRecorder) GenerateNextURLGovPay(req, paymentResource interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateNextURLGovPay", reflect.TypeOf((*MockProviderService)(nil).GenerateNextURLGovPay), req, paymentResource)
}

// GetGovPayPaymentDetails mocks base method
func (m *MockProviderService) GetGovPayPaymentDetails(paymentResource *models.PaymentResourceRest) (*models.PaymentDetails, ResponseType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGovPayPaymentDetails", paymentResource)
	ret0, _ := ret[0].(*models.PaymentDetails)
	ret1, _ := ret[1].(ResponseType)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetGovPayPaymentDetails indicates an expected call of GetGovPayPaymentDetails
func (mr *MockProviderServiceMockRecorder) GetGovPayPaymentDetails(paymentResource interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGovPayPaymentDetails", reflect.TypeOf((*MockProviderService)(nil).GetGovPayPaymentDetails), paymentResource)
}

// GetGovPayRefundSummary mocks base method
func (m *MockProviderService) GetGovPayRefundSummary(req *http.Request, id string) (*models.PaymentResourceRest, *models.RefundSummary, ResponseType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGovPayRefundSummary", req, id)
	ret0, _ := ret[0].(*models.PaymentResourceRest)
	ret1, _ := ret[1].(*models.RefundSummary)
	ret2, _ := ret[2].(ResponseType)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetGovPayRefundSummary indicates an expected call of GetGovPayRefundSummary
func (mr *MockProviderServiceMockRecorder) GetGovPayRefundSummary(req, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGovPayRefundSummary", reflect.TypeOf((*MockProviderService)(nil).GetGovPayRefundSummary), req, id)
}

// CreateRefund mocks base method
func (m *MockProviderService) CreateRefund(paymentResource *models.PaymentResourceRest, refundRequest *models.CreateRefundGovPayRequest) (*models.CreateRefundGovPayResponse, ResponseType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefund", paymentResource, refundRequest)
	ret0, _ := ret[0].(*models.CreateRefundGovPayResponse)
	ret1, _ := ret[1].(ResponseType)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateRefund indicates an expected call of CreateRefund
func (mr *MockProviderServiceMockRecorder) CreateRefund(paymentResource, refundRequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefund", reflect.TypeOf((*MockProviderService)(nil).CreateRefund), paymentResource, refundRequest)
}
